export const countryCodeToData: { [key: string]: { name: string; flag: string } } = {
  US: { name: 'USA', flag: '🇺🇸' },
  BR: { name: 'Brasil', flag: '🇧🇷' },
  MX: { name: 'Mexico', flag: '🇲🇽' },
  AR: { name: 'Argentina', flag: '🇦🇷' },
  CO: { name: 'Colombia', flag: '🇨🇴' },
  PE: { name: 'Peru', flag: '🇵🇪' },
  ES: { name: 'Spain', flag: '🇪🇸' },
  VE: { name: 'Venezuela', flag: '🇻🇪' },
  CL: { name: 'Chile', flag: '🇨🇱' },
  EC: { name: 'Ecuador', flag: '🇪🇨' },
  GT: { name: 'Guatemala', flag: '🇬🇹' },
  BO: { name: 'Bolivia', flag: '🇧🇴' },
  DO: { name: 'Dominican Republic', flag: '🇩🇴' },
  HN: { name: 'Honduras', flag: '🇭🇳' },
  PY: { name: 'Paraguay', flag: '🇵🇾' },
  SV: { name: 'El Salvador', flag: '🇸🇻' },
  NI: { name: 'Nicaragua', flag: '🇳🇮' },
  CR: { name: 'Costa Rica', flag: '🇨🇷' },
  PA: { name: 'Panama', flag: '🇵🇦' },
  UY: { name: 'Uruguay', flag: '🇺🇾' },
};